name: schbody

services:
  app:
    build:
      context: .
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    env_file:
      - .env.example1
    restart: always
    networks:
      - schbody-network
    depends_on:
      - db

  db:
    image: postgres:13.10
    env_file:
      - .env.example1
    restart: always
    volumes:
      - schbody_db_folder:/var/lib/postgresql/data
    networks:
      - schbody-network

volumes:
  schbody_db_folder:
    external: true

networks:
  schbody-network:
