name: schbody

services:
  app:
    build:
      context: .
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    env_file:
      - .env
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13.10
    env_file:
      - .env
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - schbody_db_folder:/var/lib/postgresql/data

volumes:
  schbody_db_folder:
