name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    name: Run Playwright tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: corepack enable && corepack prepare yarn@4.5.1 --activate && yarn install

      - name: Install Playwright Browsers
        working-directory: apps/frontend
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        working-directory: apps/frontend
        run: yarn playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
